var searchData=
[
  ['t_20¹ö_20rzûùæ_20bt_20_24§é_20yd_20qd_24u_20ò_20_0',['HÄÐÝ5ÖÄÏ\^«µ $&amp;SSõA\DÖ+,ZZ0|dÑJRó -AM  ¤ug° E{iÀZ&amp;u.âI¾&lt;ÈIÀW#ÖàiC$F)¤P©bDÚá ° óµOóAòÁÈäÌ3 d#&gt;±Clµ U&lt;]jãFàù&amp;ð ²PÓHOaÅP²&gt;bVÄSÅmÐdtGó*ÀjÅmÕ´%Õ6°Z£¿Yq|fa-Ç®hFÆ&amp;I?ÛÌÄö5J¤ïcÂ&quot;V -Ñ:Î¦1.r³t,GA$l6àh1Ç1Ú0cÅÕßÄp¤á5ë!úÊxG[ÿG* 9ÅÐÌãYÔ[&lt;ÄD?ÇZ±CúL®¤ÃãM&gt;-º:¸¤átºk:2!ÅQG-i1.ÜÀDÐ8Ækãõ,2.dkIç}¹ãëßØ$-Ñº=õëÞdK»sÀáp8#A$_©&lt;´¡K¤#âÊ@A t&lt;¹öRzûÙÆ    bT,$§éyd;%Qd$U}ò&lt;',['../D:/ProgrammingFolder/BasGate/Documentation/Source/terms.markdown#häðý5öäïµ-ssõadözz0dñjró--am--ug-eià-zuâi¾èiàwöàicfpbdúá-óµoóaòáèäì3-dclµ-ujãfàùð-²póhoaåp²bväsåmðdtgóàjåmõõ6zyqfa-çh-fæiûìäö5jïcâv--ñî1r³tgal6àh1ç1ú0cåõßäpá5ëúêxgÿg-9åðìãyôädçzcúlããm-ºátºk2åqg-i1üàdð8ækãõ2dkiç¹ãëßø-ñºõëþdksàáp8a_kâêa-t¹örzûùæ----btéydqduò',1,'']]],
  ['table_1',['table',['../md__source_2_s_d_k_2_merchant_01first_01draft_01_s_d_k.html#gloasry-table',1,'Gloasry Table'],['../md__source_2_s_d_k_2_merchant_01first_01draft_01_s_d_k111111.html#gloasry-table-1',1,'Gloasry Table']]],
  ['table_20of_20contents_2',['Table of Contents',['../md__source_2_s_d_k_2_merchant_01first_01draft_01_s_d_k.html',1,'']]],
  ['table_20of_20contents_20table_20of_20contents_20toc_20heading_3',['Table of Contents {#table-of-contents .TOC-Heading}',['../md__source_2_s_d_k_2_merchant_01first_01draft_01_s_d_k111111.html#table-of-contents-table-of-contents-toc-heading',1,'']]],
  ['table_20of_20contents_20toc_20heading_4',['Table of Contents {#table-of-contents .TOC-Heading}',['../md__source_2_s_d_k_2_merchant_01first_01draft_01_s_d_k111111.html#table-of-contents-table-of-contents-toc-heading',1,'']]],
  ['terms_5',['terms',['../terms.html',1,'']]],
  ['to create_20your_20mini_20app_6',['to create your mini app',['../md__source_2_s_d_k_2_merchant_01first_01draft_01_s_d_k.html#easy-3-step process-to create-your-mini-app',1,'Easy 3-step process to create your Mini App'],['../md__source_2_s_d_k_2_merchant_01first_01draft_01_s_d_k111111.html#easy-3-step process-to create-your-mini-app-1',1,'Easy 3-step process to create your Mini App']]],
  ['to_20security_20reasons_7',['3005                 Failure      Blocked due to security reasons',['../md__source_2_s_d_k_2_merchant_01first_01draft_01_s_d_k111111.html#autotoc_md3005-----------------failure------blocked-due-to-security-reasons',1,'']]],
  ['toc_20heading_8',['Table of Contents {#table-of-contents .TOC-Heading}',['../md__source_2_s_d_k_2_merchant_01first_01draft_01_s_d_k111111.html#table-of-contents-table-of-contents-toc-heading',1,'']]],
  ['transaction_20order_20api_9',['transaction order api',['../md__source_2_s_d_k_2_merchant_01first_01draft_01_s_d_k.html#post-initiate-transaction-order-api',1,'POST: initiate Transaction Order API'],['../md__source_2_s_d_k_2_merchant_01first_01draft_01_s_d_k111111.html#post-initiate-transaction-order-api-1',1,'POST: initiate Transaction Order API']]],
  ['transaction_20status_10',['transaction status',['../md__source_2_s_d_k_2_merchant_01first_01draft_01_s_d_k.html#body-transaction-status',1,'Body Transaction Status'],['../md__source_2_s_d_k_2_merchant_01first_01draft_01_s_d_k111111.html#body-transaction-status-1',1,'Body Transaction Status']]],
  ['transaction_20status_20api_11',['transaction status api',['../md__source_2_s_d_k_2_merchant_01first_01draft_01_s_d_k.html#post-check-transaction-status-api',1,'POST: check Transaction Status API'],['../md__source_2_s_d_k_2_merchant_01first_01draft_01_s_d_k111111.html#post-check-transaction-status-api-1',1,'POST: check Transaction Status API']]]
];
